### ISSUE TITLE
panic: you must set env variable LABEL

### ISSUE THREAD

**Issue by Pixelartist** [vmorganp/Lazytainer#33]
Running the "Test it Guide" leads to this error:

```
D:\projects\Lazytainer> docker-compose up
[+] Running 3/0
 ✔ Container lazytainer  Created                                                                                                                              0.0s 
 ✔ Container whoami1     Created                                                                                                                              0.0s 
 ✔ Container whoami2     Created                                                                                                                              0.0s 
Attaching to lazytainer, whoami1, whoami2
lazytainer  | panic: you must set env variable LABEL
lazytainer  |
lazytainer  | goroutine 1 [running]:
lazytainer  | main.setVarsFromEnv()
lazytainer  |   /root/lazytainer.go:76 +0x51d
lazytainer  | main.main()
lazytainer  |   /root/lazytainer.go:26 +0x2e
lazytainer  |
lazytainer exited with code 2
Error response from daemon: cannot join network of a non running container: f371e8d50992827ea2cd2844c0616b09f49543b55893791e8d47e0724b53c08a
```

I am on windows, latest everything.

**Comment by vmorganp** [comment]
Can you run a `git rev-parse HEAD` in the the root of the cloned repo and provide the output here?
